
[project]
name = "broca"
version = "0.1.0"
description = "A lightweight agent framework"
authors = [
    {name = "Rossi",email = "1142595193@qq.com"}
]
requires-python = ">=3.12,<4.0"
dependencies = [
    "litellm (>=1.81.1,<2.0.0)",
    "loguru (>=0.7.3,<0.8.0)",
    "jinja2 (>=3.1.6,<4.0.0)",
    "python-socketio[asyncio] (>=5.16.0,<6.0.0)",
    "uvicorn (>=0.40.0,<0.41.0)",
    "tree-sitter (>=0.25.2,<0.26.0)",
    "tree-sitter-bash (>=0.25.1,<0.26.0)",
    "rich (>=14.3.2,<15.0.0)",
    "asyncio-throttle (>=1.0.2,<2.0.0)",
    "textual (>=7.5.0,<8.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
