"""add_session_category

Revision ID: 0772c86c3a46
Revises: add_crew_execution_models
Create Date: 2026-05-26 10:45:03.930593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0772c86c3a46'
down_revision: Union[str, Sequence[str], None] = 'add_crew_execution_models'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blackboard_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blackboard_entry_entry_id'))
        batch_op.create_index(batch_op.f('ix_blackboard_entry_entry_id'), ['entry_id'], unique=False)

    with op.batch_alter_table('crew_execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crew_execution_execution_id'))
        batch_op.create_index(batch_op.f('ix_crew_execution_execution_id'), ['execution_id'], unique=False)

    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), server_default='normal', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('crew_execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crew_execution_execution_id'))
        batch_op.create_index(batch_op.f('ix_crew_execution_execution_id'), ['execution_id'], unique=1)

    with op.batch_alter_table('blackboard_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blackboard_entry_entry_id'))
        batch_op.create_index(batch_op.f('ix_blackboard_entry_entry_id'), ['entry_id'], unique=1)

    # ### end Alembic commands ###
