"""init_database

Revision ID: 259719598877
Revises: 
Create Date: 2026-05-28 15:38:08.027546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '259719598877'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('session',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('workspace', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('category', sa.String(), server_default='normal', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('session_id')
    )
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_session_session_id'), ['session_id'], unique=False)

    op.create_table('agent_config',
    sa.Column('config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('config_content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('config_id')
    )
    with op.batch_alter_table('agent_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_config_config_id'), ['config_id'], unique=False)

    op.create_table('crew_execution',
    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('crew_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('orchestrator_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('yaml_content', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'ABORTED', name='crewexecutionstatus'), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('result_json', sa.JSON(), nullable=True),
    sa.Column('phases_json', sa.JSON(), nullable=True),
    sa.Column('phases_total', sa.Integer(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    with op.batch_alter_table('crew_execution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crew_execution_execution_id'), ['execution_id'], unique=False)

    op.create_table('session_runner',
    sa.Column('runner_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ipc_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ipc_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(), nullable=True),
    sa.Column('restart_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('resource_info', sa.JSON(), nullable=True),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('runner_id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('task',
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('parent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'BLOCKED', 'COMPLETED', name='taskstatus'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='taskpriority'), nullable=False),
    sa.Column('assignee', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('acceptance_criteria', sa.JSON(), nullable=True),
    sa.Column('context_files', sa.JSON(), nullable=True),
    sa.Column('context_links', sa.JSON(), nullable=True),
    sa.Column('context_notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('report', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['task.task_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('task_id')
    )
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_task_task_id'), ['task_id'], unique=False)

    op.create_table('agent',
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('config_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('total_input_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_output_tokens', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_llm_calls', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_context_length', sa.Integer(), nullable=True),
    sa.Column('agent_status', sa.String(), server_default='disconnected', nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_id'], ['agent_config.config_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('agent_id')
    )
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_agent_id'), ['agent_id'], unique=False)

    op.create_table('blackboard_entry',
    sa.Column('entry_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value_json', sa.JSON(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('producer', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['crew_execution.execution_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('entry_id')
    )
    with op.batch_alter_table('blackboard_entry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_blackboard_entry_entry_id'), ['entry_id'], unique=False)

    op.create_table('task_comment',
    sa.Column('comment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.task_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('scheduled_job',
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_type', sa.Enum('REMINDER', 'COMMAND', name='jobtype'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('trigger_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('trigger_config', sa.JSON(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('next_run_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.agent_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('job_id')
    )
    op.create_table('turn',
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('turn_description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.agent_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('turn_id')
    )
    with op.batch_alter_table('turn', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_turn_turn_id'), ['turn_id'], unique=False)

    op.create_table('job_execution',
    sa.Column('execution_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('job_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('executed_at', sa.DateTime(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('result', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['scheduled_job.job_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('execution_id')
    )
    op.create_table('message',
    sa.Column('message_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sa.Enum('AGENT_SYSTEM_MESSAGE', 'CONNECT', 'DISCONNECT', 'PING', 'PONG', 'ERROR', 'USER_MESSAGE', 'AGENT_RESPONSE', 'AGENT_ERROR', 'SYSTEM_MESSAGE', 'AGENT_QUERY', 'USER_ANSWER', 'TOOL_CALL', 'TASK_START', 'TASK_COMPLETE', 'TASK_ERROR', 'TURN_START', 'TURN_END', 'STEP_START', 'STEP_END', 'SUBSCRIBE', 'UNSUBSCRIBE', 'BROADCAST', 'COMMAND', 'COMMAND_RESULT', 'PERMISSION_REQUEST', 'PERMISSION_RESPONSE', name='messagetype'), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('sender_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('receiver_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('room', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('subscription', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('session_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('turn_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('agent_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('execution_id', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', 'TOOL', 'AGENT_SYSTEM', 'AGENT', name='messagerole'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=True),
    sa.Column('reverted', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_expired', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_truncated', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agent.agent_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['session.session_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['turn_id'], ['turn.turn_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_message_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_message_message_id'), ['message_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_message_message_id'))
        batch_op.drop_index(batch_op.f('ix_message_execution_id'))

    op.drop_table('message')
    op.drop_table('job_execution')
    with op.batch_alter_table('turn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turn_turn_id'))

    op.drop_table('turn')
    op.drop_table('scheduled_job')
    op.drop_table('task_comment')
    with op.batch_alter_table('blackboard_entry', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_blackboard_entry_entry_id'))

    op.drop_table('blackboard_entry')
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_agent_id'))

    op.drop_table('agent')
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_task_task_id'))

    op.drop_table('task')
    op.drop_table('session_runner')
    with op.batch_alter_table('crew_execution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crew_execution_execution_id'))

    op.drop_table('crew_execution')
    with op.batch_alter_table('agent_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_config_config_id'))

    op.drop_table('agent_config')
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_session_session_id'))

    op.drop_table('session')
    # ### end Alembic commands ###
