"""add

Revision ID: 4e68c0e26dd1
Revises:
Create Date: 2026-05-27 15:25:36.526637

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e68c0e26dd1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("crew_execution", schema=None) as batch_op:
        batch_op.add_column(sa.Column("phases_total", sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column("progress", sa.Float(), nullable=True))

    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("fk_session_runner_id"), type_="foreignkey")
        batch_op.drop_column("runner_id")
        batch_op.drop_column("runner_status")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("session", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "runner_status",
                sa.VARCHAR(),
                server_default=sa.text("'none'"),
                nullable=False,
            )
        )
        batch_op.add_column(sa.Column("runner_id", sa.VARCHAR(), nullable=True))
        batch_op.create_foreign_key(
            batch_op.f("fk_session_runner_id"),
            "session_runner",
            ["runner_id"],
            ["runner_id"],
            ondelete="SET NULL",
        )

    with op.batch_alter_table("crew_execution", schema=None) as batch_op:
        batch_op.drop_column("progress")
        batch_op.drop_column("phases_total")

    # ### end Alembic commands ###
