"""add_ipc_family

Revision ID: 7a8e71586536
Revises: d42f82c31bd6
Create Date: 2026-04-29 09:59:09.876804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7a8e71586536'
down_revision: Union[str, Sequence[str], None] = 'd42f82c31bd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_runner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ipc_family', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session_runner', schema=None) as batch_op:
        batch_op.drop_column('ipc_family')

    # ### end Alembic commands ###
