"""add_field

Revision ID: 8f4bac3ca052
Revises: 
Create Date: 2026-04-28 12:41:58.018547

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8f4bac3ca052'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runner_id', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('runner_status', sa.String(), server_default='none', nullable=False))
        batch_op.create_foreign_key('fk_session_runner_id', 'session_runner', ['runner_id'], ['runner_id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint('fk_session_runner_id', type_='foreignkey')
        batch_op.drop_column('runner_status')
        batch_op.drop_column('runner_id')

    # ### end Alembic commands ###
