"""add_crew_execution_models

Revision ID: add_crew_execution_models
Revises: b58c35873f68
Create Date: 2026-05-25 15:30:00.000000
"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "add_crew_execution_models"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic ###

    # CrewExecution 表
    op.create_table(
        "crew_execution",
        sa.Column("execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("session_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("crew_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "orchestrator_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column("yaml_content", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "status",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="pending",
        ),
        sa.Column("error_message", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("result_json", sa.JSON(), nullable=True),
        sa.Column("phases_json", sa.JSON(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["session_id"], ["session.session_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("execution_id"),
    )
    op.create_index(
        op.f("ix_crew_execution_execution_id"),
        "crew_execution",
        ["execution_id"],
        unique=True,
    )

    # BlackboardEntry 表
    op.create_table(
        "blackboard_entry",
        sa.Column("entry_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("execution_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("value_json", sa.JSON(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False, server_default="0"),
        sa.Column(
            "producer",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="system",
        ),
        sa.Column(
            "event_type",
            sqlmodel.sql.sqltypes.AutoString(),
            nullable=False,
            server_default="created",
        ),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["execution_id"], ["crew_execution.execution_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("entry_id"),
    )
    op.create_index(
        op.f("ix_blackboard_entry_entry_id"),
        "blackboard_entry",
        ["entry_id"],
        unique=True,
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic ###
    op.drop_index(
        op.f("ix_blackboard_entry_entry_id"),
        table_name="blackboard_entry",
    )
    op.drop_table("blackboard_entry")
    op.drop_index(
        op.f("ix_crew_execution_execution_id"),
        table_name="crew_execution",
    )
    op.drop_table("crew_execution")
