"""remove_status

Revision ID: b58c35873f68
Revises: 7a8e71586536
Create Date: 2026-04-29 12:10:53.713366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'b58c35873f68'
down_revision: Union[str, Sequence[str], None] = '7a8e71586536'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_session_runner_id'), type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('runner_id')
        batch_op.drop_column('runner_status')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('session', schema=None) as batch_op:
        batch_op.add_column(sa.Column('runner_status', sa.VARCHAR(), server_default=sa.text("'none'"), nullable=False))
        batch_op.add_column(sa.Column('runner_id', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=8), nullable=False))
        batch_op.create_foreign_key(batch_op.f('fk_session_runner_id'), 'session_runner', ['runner_id'], ['runner_id'], ondelete='SET NULL')

    # ### end Alembic commands ###
