"""update_agent

Revision ID: d42f82c31bd6
Revises: 8f4bac3ca052
Create Date: 2026-04-28 16:06:32.245803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd42f82c31bd6'
down_revision: Union[str, Sequence[str], None] = '8f4bac3ca052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('agent_status', sa.String(), server_default='disconnected', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent', schema=None) as batch_op:
        batch_op.drop_column('agent_status')

    # ### end Alembic commands ###
