"""add_turn_execution_id_field

Revision ID: fcc46ff4e8f8
Revises: 26aa1804a2d6
Create Date: 2026-06-18 22:33:14.106364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fcc46ff4e8f8'
down_revision: Union[str, Sequence[str], None] = '26aa1804a2d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn', schema=None) as batch_op:
        batch_op.add_column(sa.Column('execution_id', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_turn_execution_id'), ['execution_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('turn', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_turn_execution_id'))
        batch_op.drop_column('execution_id')

    # ### end Alembic commands ###
