from jinja2 import Template

from broca.commands.base import CommandContext, CommandResult, LocalCommand
from broca.logging_config import get_logger
from broca.skill.skill_evolution import run_skill_sub_agent

logger = get_logger(__name__)

ALLOWED_TOOLS = [
    "skill_manage",
    "load_skill",
    "read_file",
    "glob",
    "grep",
    "list_dir",
    "tree_dir",
    "web_fetch",
    "web_search",
    "bash",
    "ask_user",
]

CREATE_PROMPT_TEMPLATE = Template("""\
Your task is to create a new Skill based on the conversation above.

## Instructions

{% if skill_name -%}
1. Analyze the conversation history and identify patterns, workflows, or processes that would be valuable to reuse as a Skill.
2. Create a new Skill named `{{ skill_name }}` using the `skill_manage` tool with action="create".
{%- else -%}
1. Analyze the conversation history and identify a topic/pattern that would make a good reusable Skill.
2. Come up with a concise, descriptive name for the Skill (use 2-4 words, kebab-case).
3. Create the Skill using the `skill_manage` tool with action="create".
{%- endif %}
   - name: "{{ skill_name or '<auto-generated>' }}" (will be auto-cleaned to slug format)
   - content: Full SKILL.md content following the format below

{% if description %}
The user described this skill as: {{ description }}
{% endif %}

## SKILL.md Format

The SKILL.md must have YAML frontmatter and a body:

```markdown
---
name: {{ skill_name or '<skill-name>' }}
description: One-sentence description of what this skill does and when to invoke (keep it concise)
---

## When to Use
(Describe when this skill should be invoked)

## Steps
1. ...
2. ...
3. ...

## Notes
- ...
```

## Quality Checklist

- The `description` field must be clear and specific for search matching
- Steps must be concrete and actionable
- Include all necessary context for someone (or another Agent) to execute the skill
- Do NOT create a skill that duplicates existing functionality
- Check existing skills via `load_skill` if needed
- Do NOT reference session-specific details (message IDs, timestamps) in the skill

## Constraints

- Only use the `skill_manage` tool to create the skill
{% if skill_name -%}
- If name "{{ skill_name }}" already exists, report it and stop
{%- else -%}
- If the name you choose already exists, try a different name or append a distinguishing suffix
{%- endif %}
- Create exactly ONE skill per invocation
""")


class SkillCreateCommand(LocalCommand):
    """创建新 Skill"""

    async def execute(self, args: str, ctx: CommandContext) -> CommandResult:
        parts = args.strip().split(None, 1)
        skill_name = parts[0] if parts else ""
        description = parts[1] if len(parts) > 1 else ""

        prompt = CREATE_PROMPT_TEMPLATE.render(
            skill_name=skill_name if skill_name else None,
            description=description,
        )

        success, msg = await run_skill_sub_agent(
            agent=ctx.agent,
            prompt=prompt,
            allowed_tools=ALLOWED_TOOLS,
        )

        if success:
            label = f"'{skill_name}'" if skill_name else "(auto-named)"
            return CommandResult(
                type="text",
                value=f"✅ Skill {label} creation completed.\n{msg}",
            )
        else:
            return CommandResult(
                type="error",
                value=f"❌ Skill creation failed: {msg}",
            )
